dbt_ecommerce:
  outputs:
    postgres:
      type: postgres
      threads: 1
      host: "{{ env_var('DB_HOST') }}"
      port: "{{ env_var('DB_PORT') | as_number }}"
      user: "{{ env_var('DB_USER') }}"
      pass: "{{ env_var('DB_PASSWORD') }}"
      dbname: "{{ env_var('DB_NAME') }}"
      schema: "{{ env_var('DB_SCHEMA') }}"
  target: postgres